### ISSUE TITLE
integration with webpack-dashboard

### ISSUE THREAD

**Issue by havenchyk** [geowarin/friendly-errors-webpack-plugin#13]
Hi, thanks for your work on wonderful package.

But is it possible to integrate this plugin with webpack-dashboard?

**Comment by geowarin** [comment]
Hello @havenchyk.

I've never used webpack-dashboard but it looks the purpose of the project is to redecorate the console output.
It thus seems to conflict with this plugin because it also wants to write errors and warnings to the console.

You'll have to give it a try but if webpack-dashboard doesn't provide a plugin system, I think it just won't work.
Keep us posted with your progress and let me know if I can do anything to help.

**Comment by havenchyk** [comment]
@geowarin thanks for the answer. Basically I saw a mention of webpack-dashboard in readme, so I thought you had a try at least. Anyway, thanks
