### ISSUE TITLE
Warning not handled

### ISSUE THREAD

**Issue by mrasoahaingo** [geowarin/friendly-errors-webpack-plugin#7]
Got this error on the browser debugger console that is not displayed on the terminal:

**Browser**

<img width="751" alt="capture d ecran 2016-09-08 a 17 02 41" src="https://cloud.githubusercontent.com/assets/12088397/18354521/3003876a-75e6-11e6-9022-5d2942cb707c.png">

**Terminal**

<img width="579" alt="capture d ecran 2016-09-08 a 17 04 03" src="https://cloud.githubusercontent.com/assets/12088397/18354547/48910078-75e6-11e6-9a84-ffa273c2ad5f.png">

Thanks :)

**Comment by geowarin** [comment]
Hello @mrasoahaingo!

React runtime errors are never displayed in the terminal. 
So that's the expected behaviour for now.

I guess we could try to improve that but that would be difficult. It would require wrapping the console on the browser side and maintain some kind of websocket connection to send browser errors to webpack.
The best place to handle that would be webpack-dev-middleware I guess.

**Comment by mrasoahaingo** [comment]
Fair enough, let's close this
